WIP Commit of Cognito functionality for PHA verification UI.
covidgreen/covid-green-push-api pull request #15
Opened 2020-08-25 07:31 UTC by mikegwhit

2020-08-25 19:22 UTC, negronjl approved these changes

2020-08-25 19:22 UTC, negronjl commented on .env.sample
> +COGNITO_POOL_ID=
Needs a newline here

2020-08-25 19:22 UTC, negronjl commented on lib/routes/pha-verification/index.js
> +            // TODO: If production, then squelch error.
Why squelch in production ?

2020-08-25 19:56 UTC, segfault requested changes
In general LGTM. Needs secret and parameter store via config for settings.

2020-08-25 19:56 UTC, segfault commented on lib/routes/pha-verification/index.js
> +            // TODO: If production, then squelch error.
functionally what happens when we fail here?

2020-08-25 19:56 UTC, segfault commented on lib/routes/pha-verification/index.js
> +          url: `https://cognito-idp.${process.env.AWS_REGION}.amazonaws.com/${process.env.COGNITO_POOL_ID}/.well-known/jwks.json`,
Is the usage of env vars for things like COGNITO_POOL_ID consistent with the other behavior here. This will require a terraform change in the covid-green-infra repo to match

2020-08-25 19:56 UTC, segfault commented on lib/routes/pha-verification/index.js
> +      request.headers.authorization = `Bearer ${process.env.PUSH_TOKEN}`
Same question regarding env vars

2020-08-25 19:56 UTC, segfault commented on lib/routes/pha-verification/index.js
> +    UserPoolId: process.env.COGNITO_POOL_ID,
It looks like this should be getting pulled from the config to match existing behavior.

2020-08-25 20:05 UTC, colmharte requested changes

2020-08-25 20:05 UTC, colmharte commented on lib/routes/pha-verification/index.js
> +                        resolve({
The response will be 200 but contain the err? The error should not be returned to caller

2020-08-25 20:05 UTC, colmharte commented on lib/routes/pha-verification/index.js
> +                const phone = request.body.phone.replace(/[\-]+/g, '');
This is handled by the notify/positive method, no need to enforce here

2020-08-25 20:05 UTC, colmharte commented on lib/routes/pha-verification/index.js
> +    if (!config.isProduction) {
What is the purpose of this, isProduction will be true in all deployed envs

2020-08-25 20:05 UTC, colmharte commented on lib/routes/pha-verification/index.js
> +                            response.status(200);
Is this needed?

2020-08-25 20:05 UTC, colmharte commented on lib/routes/pha-verification/index.js
> +        url: '/pha/check',
What is this used for?

2020-08-25 20:05 UTC, colmharte commented on lib/routes/pha-verification/index.js
> +        let data;
This doesn't need to be outside the try block

2020-08-25 20:05 UTC, colmharte commented on lib/routes/pha-verification/index.js
> +            data = (await axios({
Can we use node-fetch rather than axios? We use node-fetch in app api repo so be good to be consistent

2020-08-25 20:05 UTC, colmharte commented on lib/routes/pha-verification/index.js
> +                    err: 'Invalid session token.'
Lets change the text so we can distinguish from previous error

2020-08-25 20:05 UTC, colmharte commented on lib/routes/pha-verification/index.js
> +                            err: 'Invalid session token.'
Same as above

2020-08-25 20:05 UTC, colmharte commented on lib/routes/pha-verification/index.js
> +                    err: 'Not authorized'
No need for text here, just `throw new Unauthorized()`

2020-08-25 20:05 UTC, colmharte commented on package.json
> +    "cross-fetch": "^3.0.5",
Is this being used?

2020-08-25 20:05 UTC, colmharte commented on lib/routes/pha-verification/index.js
> +                url: `https://cognito-idp.${process.env.AWS_REGION}.amazonaws.com/${process.env.COGNITO_POOL_ID}/.well-known/jwks.json`,
AWS_REGION should be read into config and config referenced here

2020-08-25 20:05 UTC, colmharte commented on lib/routes/pha-verification/index.js
> +            const isValidSession = await checkSession(token);
Have a look at the notify/positive route and how authorisation is checked, be good to use same pattern here

2020-08-25 20:05 UTC, colmharte commented on lib/routes/pha-verification/index.js
> +                    error: err.data.message
Error text should not be returned

2020-08-25 20:05 UTC, colmharte commented on lib/routes/pha-verification/index.js
> +            const config = await getConfig();
Config is available through  options, no need to load it again

2020-08-25 20:05 UTC, colmharte commented on lib/routes/pha-verification/index.js
> +    const config = await getConfig();
`options` contains the config data

2020-08-28 16:14 UTC, mikegwhit commented on lib/routes/pha-verification/index.js
> +    const config = await getConfig();
Should be done in the next commit i push

2020-08-28 16:15 UTC, mikegwhit commented on lib/routes/pha-verification/index.js
> +            const config = await getConfig();
Same as below fixed in next push

2020-08-28 16:15 UTC, mikegwhit commented on lib/routes/pha-verification/index.js
> +                    error: err.data.message
This should just now act as a dumb proxy.

2020-08-28 16:16 UTC, mikegwhit commented on lib/routes/pha-verification/index.js
> +            const isValidSession = await checkSession(token);
We now reuse the auth of notify.  We additionally layer in the Cognito session check.

2020-08-28 16:16 UTC, mikegwhit commented on lib/routes/pha-verification/index.js
> +                url: `https://cognito-idp.${process.env.AWS_REGION}.amazonaws.com/${process.env.COGNITO_POOL_ID}/.well-known/jwks.json`,
Seeking clarification @colmharte because our config in production seems to likewise indicate that AWS_REGION is set in process.env.  happy to add this into config otherwise.  pls advise thoughts.

2020-08-28 16:17 UTC, mikegwhit commented on lib/routes/pha-verification/index.js
> +        url: '/pha/check',
We can put this into the development build but basically this just checks the session token.  Pls advise if we don't want to expose via prod. @colmharte

2020-08-28 16:18 UTC, mikegwhit commented on lib/routes/pha-verification/index.js
> +                            response.status(200);
Likely not since i think status 200 is assumed if no err thrown.

2020-08-28 16:19 UTC, mikegwhit commented on lib/routes/pha-verification/index.js
> +    if (!config.isProduction) {
Ah wasn't sure if it was set to production everywhere.. was presuming based off this:

![image](https://user-images.githubusercontent.com/2973130/91590026-e42e9880-e917-11ea-80cc-6b006ad38ca0.png)

2020-08-28 16:19 UTC, mikegwhit commented on lib/routes/pha-verification/index.js
> +                const phone = request.body.phone.replace(/[\-]+/g, '');
Now dumbly proxying to notify endpoint logic.

2020-08-28 21:58 UTC, mikegwhit commented on lib/routes/pha-verification/index.js
> +            // TODO: If production, then squelch error.
This just returns an error to app.  Could throw a Forbidden instead.

2020-08-28 21:58 UTC, mikegwhit commented on lib/routes/pha-verification/index.js
> +          url: `https://cognito-idp.${process.env.AWS_REGION}.amazonaws.com/${process.env.COGNITO_POOL_ID}/.well-known/jwks.json`,
Done

2020-08-28 21:59 UTC, mikegwhit commented on package.json
> +    "cross-fetch": "^3.0.5",
Yes, unfortunately this is an add item required by Cognito.  Just requiring it in the file enables `fetch` to be used as though it were in a browser.

2020-08-28 22:00 UTC, mikegwhit commented on lib/routes/pha-verification/index.js
> +                        resolve({
Patching to throw `Forbidden` with a generic `Login failed` msg.

2020-08-28 22:01 UTC, mikegwhit commented on lib/routes/pha-verification/index.js
> +    if (!config.isProduction) {
Resolving but pls reopen if this doesn't make sense.

2020-08-28 22:02 UTC, mikegwhit commented on lib/routes/pha-verification/index.js
> +        url: '/pha/check',
Resolving but pls reopen if unclear

2020-08-28 22:02 UTC, mikegwhit commented on lib/routes/pha-verification/index.js
> +                url: `https://cognito-idp.${process.env.AWS_REGION}.amazonaws.com/${process.env.COGNITO_POOL_ID}/.well-known/jwks.json`,
Resolving on basis that env.AWS_REGION already used elsewhere.

2020-08-28 22:03 UTC, mikegwhit commented on lib/routes/pha-verification/index.js
> +            const isValidSession = await checkSession(token);
Resolving, pls reopen if unclear

2021-01-08 10:28 UTC, closed without merging